[package]
name = "mpris-server"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
zbus = "3.14"
futures-channel = "0.3.28"

[dev-dependencies]
async-std = { version = "1.12", features = ["attributes"] }
