[package]
name = "mpris-server"
version = "0.7.0"
description = "Implement MPRIS D-Bus interface in your application"
homepage = "https://github.com/SeaDve/mpris-server"
repository = "https://github.com/SeaDve/mpris-server"
documentation = "https://docs.rs/mpris-server"
authors = ["Dave Patrick Caberto"]
categories = ["api-bindings", "multimedia", "os::unix-apis"]
keywords = ["mpris", "dbus"]
readme = "README.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures-channel = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
serde = "1.0"
zbus = "4.0"

[dev-dependencies]
async-std = { version = "1.12", features = ["attributes", "unstable"] }
static_assertions = "1.1"

[features]
unstable = []

[package.metadata.docs.rs]
features = ["unstable"]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
